# Generated by Django 3.1.3 on 2021-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0002_auto_20211210_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerboard',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\dandi\\sjumpan\\media'),
        ),
    ]
