# Generated by Django 3.1.7 on 2022-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0005_auto_20220107_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='rottenshoe/images/%Y/%m/%d'),
        ),
    ]
