# Generated by Django 4.0.1 on 2022-01-13 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0007_auto_20220109_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='score',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='cop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='sneaker_name_ko',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
