# Generated by Django 4.0.1 on 2022-01-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0008_remove_sneakers_score_comment_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('sneaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rottenshoe.sneakers')),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
    ]
