# Generated by Django 4.0.1 on 2022-01-16 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0010_sneakers_cop_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopOrDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rottenshoe.sneakers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
