# Generated by Django 4.0.1 on 2022-01-18 21:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0011_copordrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterModelTable(
            name='copordrop',
            table='CopTable',
        ),
        migrations.CreateModel(
            name='UserMovementOfViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_time', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 21, 19, 33, 559211))),
                ('sneaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rottenshoe.sneakers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_movements_of_views',
            },
        ),
    ]
