# Generated by Django 4.0.1 on 2022-02-04 00:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0012_sneakers_views_alter_copordrop_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('request_time', models.DateTimeField(default=datetime.datetime(2022, 2, 4, 0, 42, 44, 743632))),
            ],
            options={
                'db_table': 'requests_of_search',
            },
        ),
        migrations.AlterField(
            model_name='copordrop',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermovementofviews',
            name='movement_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 0, 42, 44, 743632)),
        ),
    ]
