# Generated by Django 4.0.1 on 2022-02-04 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0013_searchrequest_alter_copordrop_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 1, 38, 5, 321005)),
        ),
        migrations.AlterField(
            model_name='usermovementofviews',
            name='movement_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 1, 38, 5, 320009)),
        ),
    ]
