# Generated by Django 3.1.7 on 2022-02-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe', '0015_auto_20220215_2249'),
        ('rottenshoe_drf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SneakerRecommandData',
            new_name='SneakerFeatures',
        ),
    ]
