# Generated by Django 3.1.7 on 2022-02-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe_drf', '0002_auto_20220215_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerfeatures',
            name='comfortable',
            field=models.FloatField(default=0.0, verbose_name='편안함'),
        ),
        migrations.AlterField(
            model_name='sneakerfeatures',
            name='convenience',
            field=models.FloatField(default=0.0, verbose_name='실용성'),
        ),
        migrations.AlterField(
            model_name='sneakerfeatures',
            name='grip',
            field=models.FloatField(default=0.0, verbose_name='착화감'),
        ),
        migrations.AlterField(
            model_name='sneakerfeatures',
            name='spotlight',
            field=models.FloatField(default=0.0, verbose_name='화제성'),
        ),
    ]
