# Generated by Django 3.1.7 on 2022-02-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rottenshoe_drf', '0003_auto_20220215_2254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sneakerfeatures',
            table='sneakerFeature',
        ),
    ]
